### ISSUE TITLE
[CI/CD구축] docker 파일 생성

### ISSUE THREAD

**Issue by aerim-choi** [UniUnity-sungshin/UniUnity#6]
## 목적
> CI/CD를 구축하기 위해 `dockerfile` 생성
## 작업 상세 내용
-  UniUnity서비스 구조에 맞게 nodejs 웹서비스 dockerfile생성
## 참고 사항
강의자료 10주차

**Comment by pjhyun0225** [comment]
제가할게요

**Comment by aerim-choi** [comment]
> 제가할게요

네 ^^
