### ISSUE TITLE
[CI/CD구축] deployment.yaml 파일 생성

### ISSUE THREAD

**Issue by youngseoOh** [UniUnity-sungshin/UniUnity#7]
## 목적
> UniUnity 어플리케이션 배포 및 업데이트를 위해 `deployment.yaml`을 생성해주세요
## 작업 상세 내용
- replicas 는 2개로 해주세요.
- db정보는 쿠버네티스의 secret을 이용하여 환경변수를 관리해주세요.
## 참고 사항
강의자료10주차

**Comment by imeunyoung** [comment]
확인입니다

**Comment by aerim-choi** [comment]
제가 하겠습니다.

**Comment by aerim-choi** [comment]
확인입니다.

**Comment by pjhyun0225** [comment]
확인했습니다.
