### ISSUE TITLE
[CI/CD구축] db.js파일 쿠버네티스 시크릿파일을 불러오도록 수정해주세요

### ISSUE THREAD

**Issue by pjhyun0225** [UniUnity-sungshin/UniUnity#9]
## 목적
>  `.env`파일을 쿠버네티스 시크릿을 이용하도록 변경
## 작업 상세 내용
- 모듈 kubernetes/client-node를 이용해주세요
## 참고 사항
https://github.com/kubernetes-client/javascript/blob/master/README.md

**Comment by aerim-choi** [comment]
제가 하겠습니다.
